spring.application.name=shop
#server.port=6062
server.port=${PORT:8081}
# ===============================
# = DataSource Configuration
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# ===============================
# = JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.main.lazy-initialization=true
# The SQL dialect makes Hibernate generate better SQL for the chosen DB
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Optional: Show SQL statements in logs
spring.jpa.show-sql=true
jwt.secret= ${JWT_SECRET}
jwt.expiration-ms=3600000 

aws.region=${EU_REGION}
aws.s3.bucket-name=${S3_BUCKET_NAME}
aws.accessKeyId=${AWS_ACCESS_ID}
aws.secretAccessKey=${AWS_ACCESS_KEY}
aws.sqs.queue.name=${AWS_QUEUE_NAME}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=10000,expireAfterWrite=10m

scheduler.stockReminder.cron= 0 0/55 * * * ?
scheduler.messageRemover.cron= 0 0 0 * * ?
scheduler.paymentReminder.cron= 0 0/55 * * * ?
scheduler.subsriptionUpdate.cron= 0 0 0 * * *

razorpay.key.secret=${RAZOR_PAY_SECRET}
razorpay.key.id=${RAZOR_PAY_ID}

# Change to your region (e.g., us-east-1)
spring.cloud.aws.region.static=eu-north-1

# ONLY for local testing. In prod, Beanstalk/IAM handles this automatically!
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_ID}
spring.cloud.aws.credentials.secret-key=${AWS_ACCESS_KEY}

gemini.flash.apikey=${GEMINI_FLASH_KEY}
gemini.flash.url=${GEMINI_FLASH_URL}

