spring.application.name=shop
#server.port=9092
server.port=${PORT:8080}
logging.level.root=INFO
# ===============================
# = DataSource Configuration
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# = JPA / Hibernate Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Optional: Show SQL statements in logs
spring.jpa.show-sql=true
jwt.secret= ${JWT_SECRET}
jwt.expiration-ms=36000000 

aws.region=eu-north-1
aws.s3.bucket-name=clearbillsfiles
aws.accessKeyId=${AWS_ACCESS_ID}
aws.secretAccessKey=${AWS_ACCESS_KEY}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

google.client.id=${GOOGLE_CLIENT_ID}


smsalert.apiKey=${SMS_ALERT_APIKEY}
smsalert.baseUrl=${SMS_ALERT_BASEURL}
smsalert.senderId=${SMS_ALERT_SENDERID}

management.server.port=8082
management.endpoints.web.exposure.include=health,info,metrics,logfile,loggers,prometheus
